clone_folder: c:\project\opencpn\plugin_source
shallow_clone: false
clone_depth: 10

image:
- Visual Studio 2022

platform:
- Win32

configuration: RelWithDebInfo
test: OFF

install:
  - set "VS_HOME=C:\Program Files\Microsoft Visual Studio\2022"
  - call "%VS_HOME%\Community\VC\Auxiliary\Build\vcvars32.bat"

  # set environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.2.1
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit

  # Download and unzip wxwidgets
  - ps: Start-FileDownload https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxMSW-3.2.1_vc14x_Dev.7z
  - cmd: 7z x -oC:\wxWidgets-3.2.1 wxMSW-3.2.1_vc14x_Dev.7z
  - ps: Start-FileDownload https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1-headers.7z
  - cmd: 7z x -oC:\wxWidgets-3.2.1 wxWidgets-3.2.1-headers.7z

  # some debugging information
  - set

before_build:
  - cd c:\project\opencpn\plugin_source
  - mkdir build
  - cd build

  - cmake -A Win32 -G "Visual Studio 17 2022" ^
      -DCMAKE_GENERATOR_PLATFORM=Win32 ^
      -DwxWidgets_LIB_DIR=C:\wxWidgets-3.2.1\lib\vc14x_dll ^
      -DwxWidgets_ROOT_DIR=C:\wxWidgets-3.2.1 ^
      ..

build_script:
  - cmake -G "Visual Studio 17 2022"   ..
  - cmake --build . --target install --config RelWithDebInfo
  - cmake --build . --target package --config RelWithDebInfo
  - choco install git
  - python -m ensurepip
  - python -m pip install setuptools
  - python -m pip install cloudsmith-cli
  - bash ../ci/appveyor-upload.sh

#  - path: 'build\RelWithDebInfo\opencpn.lib'
#    name: lib
#
#  - path: 'build\RelWithDebInfo\opencpn-*.pdb'
#    name: pdb
#
#deploy:
#  description: 'release created by AppVeyor CI'
#  provider: GitHub
#  auth_token: '%GitHub_auth_token%'
#  artifact: installer,lib
#  draft: true
#  prerelease: true
#  on:
#    appveyor_repo_tag: true # deploy on tag push only
#    configuration: RelWithDebInfo  # Debug contains non-redist MS DLLs
