---
version: 2
jobs:
   build-flatpak-x86-64-1808:
     machine:
       image: circleci/classic:201808-01
     environment:
       - OCPN_TARGET:  flatpak
     steps:
       - checkout
       - run: ci/circleci-build-flatpak-x86-64-1808.sh
       - run: ci/circleci-upload-flatpak.sh
workflows:
  version: 2
  build_all:
    jobs:
       - build-flatpak-x86-64-1808:
          filters:
            branches:
              only: f86-1808
 
