---
version: 2
jobs:
   build-bionic:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - OCPN_TARGET:  bionic
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-focal:
     docker:
       - image: circleci/buildpack-deps:focal-scm
     environment:
       - OCPN_TARGET:  focal
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-jammy:
     docker:
       - image: circleci/buildpack-deps:jammy-scm
     environment:
       - OCPN_TARGET:  jammy
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-bionic-gtk3:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - BUILD_GTK3: 1
       - OCPN_TARGET:  bionic-gtk3
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-buster:
     docker:
       - image: circleci/buildpack-deps:buster-scm
     environment:
       - OCPN_TARGET:  buster
     steps:
       - checkout
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-flatpak-x86-64-2008:
     machine:
       image: circleci/classic:201808-01
     environment:
       - OCPN_TARGET:  flatpak
     steps:
       - checkout
       - run: ci/circleci-build-flatpak-x86-64-2008.sh
       - run: ci/circleci-upload-flatpak.sh
   build-macos:
     macos:
       xcode: "12.5.1"
     environment:
       - OCPN_TARGET:  macos
     steps:
       - checkout
       - restore_cache:
          keys:
            - macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
       - run: ci/circleci-build-macos.sh
       - save_cache:
          key: macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom
            - /usr/local/Cellar
            - /usr/local/lib
            - /usr/local/include
       - run: ci/circleci-upload-macos.sh

   build-arm64-debian-bullseye:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=bullseye-arm64
        - DOCKER_IMAGE=arm64v8/debian:bullseye-backports
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - BUILD_GTK3: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-debian-arm64.sh
            no_output_timeout: 30m
        - run: sh -c "python3 -m pip install --user --upgrade -q setuptools wheel pip"
        - run: sh -c "python3 -m pip install --user -q cloudsmith-cli cryptography"
        - run: sh -c "pip install --upgrade cloudsmith-cli"
        - run: sh -c "pwd; ls; cd build; ls; cd ..; /bin/bash < ci/circleci-upload.sh"

workflows:
  version: 2
  build_all:
    jobs:
      - build-bionic-gtk3:
          filters:
            branches:
              only: master
      - build-bionic:
          filters:
            branches:
              only: master
      - build-focal:
          filters:
            branches:
              only: master
      - build-jammy:
          filters:
            branches:
              only: master
      - build-buster:
          filters:
            branches:
              only: master
      - build-flatpak-x86-64-2008:
          filters:
            branches:
              only: master
      - build-macos:
          filters:
            branches:
              only: master
      - build-arm64-debian-bullseye:
          filters:
            branches:
              only: master

